### PR TITLE
Better reset support

### PR DESCRIPTION
**Pull request by rowleya**
Changes associated with SpiNNakerManchester/SpiNNFrontEndCommon#450

### CODE REVIEW

**Comment by andrewgait** [comment]
Will review this soon, but just doing some simple tests so far suggests that this is behaving more correctly than previously, but there's still something not quite right - it seems as though I can do pop.set(...) after sim.reset(), but pop.initialize(...) after sim.reset() appears to have no effect.  

(Both pop.set() and pop.initialize() correctly do nothing at present if they are called after sim.run() without a sim.reset() - it was suggested at one point that this should raise an exception but I think it's better to silently ignore it or perhaps a warning message would be a good idea?)

**Comment by rowleya** [comment]
There was an issue where I had put something in the wrong place - I believe this is now resolved.

I also got tricked when looking at this because of Neo segments.  Remember that after calling reset, the next set of data is in segments[1]...

**Comment by andrewgait** [comment]
That has fixed it.  (I was using spinnaker_get_data(..) in my script to get around the issues with neo segments...)

**Comment by andrewgait** [comment]
There's still something not quite right here.  In the new test I just pushed to the sPyNNaker8 branch at p8_integration_tests/quick_test/test_multi_call_examples/test_reset_initialize.py, if I only do a pop.initialize() between the third and fourth runs (i.e. I comment out the pop.set on line 33), then it (incorrectly) initializes the voltage to -61.  With the pop.set() included the initialize() is ignored.

**Comment by rowleya** [comment]
It should be possible to initialise without calling reset - this is just like set for state variables (I believe).  If reset is called, it should return to the values set at time == 0, so run, run, initialise, run, reset means that the values go back to before the first run I believe.  If you do run, reset, initialise, run, reset, the values should go back to just after the reset, because the time was == 0 at this point.  Set should not have an effect however, so I will look at why this is happening.

**Comment by andrewgait** [comment]
Going off the exchange at these issues: https://github.com/SpiNNakerManchester/sPyNNaker/issues/600 and https://github.com/SpiNNakerManchester/sPyNNaker/issues/599 I'd suggest that initialize() shouldn't do anything if it's not called in conjunction with reset(), or at least that's what Andrew Davison seems to be suggesting...

**Comment by rowleya** [comment]
Oops, I had forgotten about this.  OK, so initialise when time is not 0 should raise an exception.  I will update this now.

**Comment by rowleya** [comment]
OK, this has been updated and I now think it is doing the right thing!

**Comment by alan-stokes** [comment]
there seems to be some left over changes to do wtih connectors slices in here which are not related to the change mapping. 
the actual changes to change mapping im happy with.

**Comment by rowleya** [comment]
Ah, that *is* specific to this branch.  In this case, the connection slice changes are to ensure that if you reset and re-generate the connections, you should get the same connectivity as you did the first time.

**Comment by alan-stokes** [comment]
bugger must have missed that. ok fair enough

**Pull request merged**
