### PR TITLE
Atom routing from machine level

### PR DESCRIPTION
**Pull request by alan-stokes**
moves the bitfield generation of the filter for shadow packets to the chip, instead of the host.

It'll also be built upon to allow the router table compressor to try to push atom based routing from said bitfields. 

this is currently work in progress.

### CODE REVIEW

**Comment by alan-stokes** [comment]
now depends upon https://github.com/SpiNNakerManchester/PACMAN/pull/178

**Comment by alan-stokes** [comment]
depends upon https://github.com/SpiNNakerManchester/spinn_common/pull/28

**Comment by alan-stokes** [comment]
DO NOT MERGE UNLESS YA MERGED:
SpiNNakerManchester/spinn_common#28
ELSE ALL HELL SHALL BE LET LOOSE!

**Comment by alan-stokes** [comment]
ready to merge when ya merge the SpiNNakerManchester/spinn_common#28

**Comment by alan-stokes** [comment]
this needs to be reassessed with lessons learnt in bit_field router compressor. aka, structs, and delay extension mismatch between n keys and n neurons. Im inclined to throw this pr away and just handle the monster that is router compressor with bitfields...... but thats a rather big feature creep.....

**Comment by dkfellows** [comment]
Is it worth trying to mend this at all, or has it been simply overtaken by events?

**Comment by alan-stokes** [comment]
this is dead stuff. likely one of the branches of branches that accumlaed to all algorithms. which hath now been merged. so death to the zombii

**Pull request closed without merging**
