### PR TITLE
Pop views assembliers

### PR DESCRIPTION
**Pull request by alan-stokes**
mother of changes that now allows PyNN models to use PopulationViews, Assemblies and of course the basic Population. This required a rather large rewrite to models, and to be honest this is not the definite finished product. 

It includes representing neurons as atoms, and grouping them together into vertices to be used in the graph. There are currently 2 groupers, 
1. is a grouper that just puts the atoms that reside for a given population and makes them a vertex (known as a PopulationTypeGrouper)
2. is a grouper that tries to merge the atoms and populations based off model type and parameters that can be merged (known as ModelTypeGrouper). 
the ModelTypeGrouper currently exposes issues in the synaptic matrix generation due to connectors making (the up to now valid) assumption that it is applied to an entire vertex. This is no longer the case, and therefore causes issues. These issues have not been fully addressed and are left for a future work point.
- [x] build the population, pop_view and Assembly interfaces
- [x] build the atom mapping
- [x] update the basic models to handle a bag of atoms
- [x] test the record functionality of the interfaces.
- [x] test the parameter setter and getter for the interfaces.
- [x] have overall integration tests that test these logic's in tandem. 
- [x] update the input sources to work on the system.
- [x] check auto pause and resume functionality.
- [x] check multirun functionality.
- [x] check reset functionality.
- [x] check reload functionality.
- [x] refactor any epic dubious hacks. 
- [x] check all works with standard models.
- [x] update the external device models.
- [x] update the new models 
- [x] ~~update the new model template and instructions (not sure if this should be in this, or a separate bit of work).~~ 
- [ ] update docs in code

### CODE REVIEW

**Comment by dkfellows** [comment]
Needs major effort to merge; or this PR closing.

**Comment by rowleya** [comment]
Not merging as well out of date!  I'll leave the branch until we have a working version in case some ideas are useful...

**Comment by alan-stokes** [comment]
;(

**Comment by dkfellows** [comment]
The feature is desired, especially pop views, but the implementation wasn't going to work. The divergences were too much.

**Pull request closed without merging**
