### PR TITLE
Optimise getspikes

### PR DESCRIPTION
**Pull request by alan-stokes**
This again gives a pretty massive speedup

NEEDS FIXING FIRST!

### CODE REVIEW

**Comment by alan-stokes** [comment]
Jamie, this doesnt work properly. I get broken lines of synfire chains. So please fix and then respond to this pull request when done. I alas didnt test it beforehand (was distracted)

**Comment by neworderofjamie** [comment]
What example are you running?

**Comment by alan-stokes** [comment]
standard synfire script from pynn examples.

**Comment by neworderofjamie** [comment]
Good spot - No idea what you were doing with the branches so fixed it in optimise_getspikes_fix branch!

**Comment by rowleya** [comment]
This has actually been merged in via another request

**Pull request closed without merging**
