### PR TITLE
fiddled. not the cleanest, but heck

### PR DESCRIPTION
**Pull request by alan-stokes**
for ya @andrewgait

### CODE REVIEW

**Comment by Christian-B** [comment]
Do we still need/want this?

I say nuke it

**Comment by rowleya** [comment]
Looks to me to be a bit out-of-date anyway

**Comment by andrewgait** [comment]
It was an idea that ended up not being used, so yes probably best to nuke it.

**Comment by Christian-B** [comment]
nice idea but no longer needed

**Pull request closed without merging**
