### PR TITLE
when you say type use type(self). 

### PR DESCRIPTION
**Pull request by Christian-B**
Especially is self does not have _model_name!

### CODE REVIEW

**Comment by alan-stokes** [comment]
Id like to know what the output of type is instead of self._modelname. does it give you the overall odel name, or the class in which its executing?

**Comment by Christian-B** [comment]
It gives the full type hierarchy similar to what you use in import statements.
This makes finding the broken code easy!

**Comment by rowleya** [comment]
It does - type(self) is determined by the leaf in the inheritance hierarchy.  Also you need to actually *have* a self._model_name (which most code doesn't).  Note that some of the ideas for the PopulationView object might mean that you do want to look at an internal variable, but we can cross that bridge when we come to it...

**Comment by alan-stokes** [comment]
6 of 1 1/2 doz of another. id argue that finding offending code is easy with the stack trace, but i doth not hath any real care either way.

**Pull request merged**
