### PR TITLE
More exposed via global variables

### PR DESCRIPTION
**Pull request by Christian-B**
Depends on https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/762

Read configs preview before sim.setup

Make use of the extra info available through global variables.

### CODE REVIEW

**Review by rowleya — APPROVED** [review]
Agree that this makes things neater and avoids accessing _ variables!

**Comment by rowleya** [comment]
Note a branch name mismatch makes this fail

**Comment by Christian-B** [comment]
> Note a branch name mismatch makes this fail

yes I say that.

But as a sub Pr of a much bigger PR it does not really matter.
Just wanted to make sure these changes where see sperately

**Comment by rowleya** [comment]
OK - I think I merged the GFE one for some reason without merging these.  Do you want them merged?

**Comment by Christian-B** [comment]
> OK - I think I merged the GFE one for some reason without merging these. Do you want them merged?

create a FEC branch to match name so green.

Yes may as well merge as makes follow up PR cleaner. Thanks

**Pull request merged**
