### PR TITLE
Multiple executable types per run

### PR DESCRIPTION
**Pull request by alan-stokes**
supports the ability to have multiple executableTypes running on the same application. Mainly used for reinjector and extra monitor support (which are to follow pull requests in future).

depends upon FEC  this pull request
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/214

and ties into 
https://github.com/SpiNNakerManchester/SpiNNakerGraphFrontEnd/pull/70

### CODE REVIEW

**Comment by alan-stokes** [comment]
this fail in travis seems to be rooted in not finding the correct FEC branch. Can christian do his fancy magic?

**Comment by Christian-B** [comment]
This branch is incorrectly named.

Use the multiple_executable_types_per_run instead.

**Comment by Christian-B** [comment]
got confused by older branch not deleted. Farther investigation. Sorry

**Comment by dkfellows** [comment]
Looks good to me, once its dependencies are dealt with.

**Pull request merged**
