### PR TITLE
List connector optimisation

### PR DESCRIPTION
**Pull request by neworderofjamie**
This one may be slightly more controversial, but it speeds up generating big list connectors pretty massively. The previous version supported some stuff I see no sign of in the PyNN spec (http://neuralensemble.org/trac/PyNN/wiki/API-0.7#FromListConnector) - I'm not entirely certain how distributions could be validly used in the context of a list connector, but the support for the alternative 
```
[
    [pre_idx0, pre_idx1, ..., pre_idxN], 
    [pre_idx1, pre_idx2, ..., pre_idxN], 
    [weight0, weight1, ..., weightN], 
    [delay0, delay1, ..., delayN]
]
```
Format could be supported fairly trivially if there's some desire for it.

### CODE REVIEW

**Comment by alan-stokes** [comment]
Hi Jamie,

comments on your branch during code review:

first two poitns are more house keeping than issue, and thus i've already fixed them for you. But the last two are requests for yourself to impliment/discuss.

1. Please in future can you clean up your code for dangling imports, there were 5 in here which are no longer used. Ive removed these from your branch already.
2. Please refrain from making variables which are no longer used. It seems you dont use the destination vertex anymore, and yet was still being created, ive removed it for you.
3. tehre are I and J in the conn_list dtype on lines 49, 60, 81. These dont seem to be reasonable names. Would source_neuron_id and destination_neuron_id make sense?  I note that the old vesion also had this issue, but maybe a refactor would suitable that it's come to light?

4. I note that the old version had a collection of tests for if the from list connector was malformed, aka (the source and destination neuron_ids are not valid) these seem to have disappeared and now it would run and create connections which are completely malformed without warning the end user. We consider this to be a wrong behaviour in this context, as we should be checking for malformed stuff and telling the end user that they've made a mistake. Please fix this and notify me for next view. 

the test I used which verifies that the old code did raise the error and the new one doesnt is shown below, note for the line with ''''''' between it.:

"""
Synfirechain-like example
"""
import pyNN.spiNNaker as p
import pylab

p.setup(timestep=1.0, min_delay=1.0, max_delay=144.0)
nNeurons = 200  # number of neurons in each population
p.set_number_of_neurons_per_core("IF_curr_exp", nNeurons / 2)


cell_params_lif = {'cm': 0.25,
                   'i_offset': 0.0,
                   'tau_m': 20.0,
                   'tau_refrac': 2.0,
                   'tau_syn_E': 5.0,
                   'tau_syn_I': 5.0,
                   'v_reset': -70.0,
                   'v_rest': -65.0,
                   'v_thresh': -50.0
                   }

populations = list()
projections = list()

weight_to_spike = 2.0
delay = 17

loopConnections = list()
for i in range(0, nNeurons):
    singleConnection = (i, ((i + 1) % nNeurons), weight_to_spike, delay)
    loopConnections.append(singleConnection)
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
loopConnections.append((0, nNeurons + 12, weight_to_spike, delay))
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
injectionConnection = [(0, 0, weight_to_spike, 1)]
spikeArray = {'spike_times': [[0]]}
populations.append(p.Population(nNeurons, p.IF_curr_exp, cell_params_lif,
                   label='pop_1'))
populations.append(p.Population(1, p.SpikeSourceArray, spikeArray,
                   label='inputSpikes_1'))

projections.append(p.Projection(populations[0], populations[0],
                   p.FromListConnector(loopConnections)))
projections.append(p.Projection(populations[1], populations[0],
                   p.FromListConnector(injectionConnection)))

populations[0].record_v()
populations[0].record_gsyn()
populations[0].record()

p.run(5000)

v = None
gsyn = None
spikes = None

v = populations[0].get_v(compatible_output=True)
gsyn = populations[0].get_gsyn(compatible_output=True)
spikes = populations[0].getSpikes(compatible_output=True)

if spikes is not None:
    print spikes
    pylab.figure()
    pylab.plot([i[1] for i in spikes], [i[0] for i in spikes], ".")
    pylab.xlabel('Time/ms')
    pylab.ylabel('spikes')
    pylab.title('spikes')
    pylab.show()
else:
    print "No spikes received"

# Make some graphs

if v is not None:
    ticks = len(v) / nNeurons
    pylab.figure()
    pylab.xlabel('Time/ms')
    pylab.ylabel('v')
    pylab.title('v')
    for pos in range(0, nNeurons, 20):
        v_for_neuron = v[pos * ticks: (pos + 1) * ticks]
        pylab.plot([i[2] for i in v_for_neuron])
    pylab.show()

if gsyn is not None:
    ticks = len(gsyn) / nNeurons
    pylab.figure()
    pylab.xlabel('Time/ms')
    pylab.ylabel('gsyn')
    pylab.title('gsyn')
    for pos in range(0, nNeurons, 20):
        gsyn_for_neuron = gsyn[pos * ticks: (pos + 1) * ticks]
        pylab.plot([i[2] for i in gsyn_for_neuron])
    pylab.show()

p.end()

**Comment by AlexRast** [comment]
Just a small note; see below.

On 02/07/15 11:42, Alan Stokes wrote:
> Hi Jamie,
>
> comments on your branch during code review:
>  3.
>
>     tehre are I and J in the conn_list dtype on lines 49, 60, 81. These dont
>     seem to be reasonable names. Would source_neuron_id and
>     destination_neuron_id make sense? I note that the old vesion also had this
>     issue, but maybe a refactor would suitable that it's come to light?

Actually, from the point of view of neural modellers, I and J are *precisely* 
the right "reasonable names". In fact, maybe surprisingly to some, the terms 
"source_neuron_id" and "destination_neuron_id" would actually be *more* 
confusing to the community. The use of I and J to refer to pre- and 
post-synaptic neural populations (and indices) is ancient and hallowed tradition 
by this point: *everybody* knows what they mean. I'd vote for retaining the same 
names.

**Comment by alan-stokes** [comment]
Hi Alex, 

as mentioned to you in person. This bit of code is not accessable by the neural modellers. Its supproted by the computer scientsits, to which i and j are NOT valid names unless its actually a attrbitue i and j. The fact that soruce neuron id and dest neuron id can be easily replaced there. And this needs to be maintainable by cs, not neuroscentsits.

**Comment by rowleya** [comment]
I have fixed the issues and am going to merge this now

**Pull request merged**
