### PR TITLE
Fix typo in ssp

### PR DESCRIPTION
**Pull request by alan-stokes**
typo fix

### CODE REVIEW

**Comment by alan-stokes** [comment]
lol, must have been brnached off chip-power-monitor. oh well. could monkey patch it, or wait till that functionality is done. lol

**Comment by rowleya** [comment]
The choice is either to remove them here and then this will be merged in, or else wait for the merge that actually includes these changes before merging this in.  I don't mind which, but I don't think it should go in as-is to the current master.

**Comment by alan-stokes** [comment]
i concur. 6 of one 6 of a other, im happy to wait, it was only detected whilst i was trying to tie in buffer management for the chip monitor core. its not exactly fixing a bug, but more obaying our convention of not having magic numbers.

**Comment by dkfellows** [comment]
Fixed on `master`.

**Pull request closed without merging**
