### PR TITLE
Fix save

### PR DESCRIPTION
**Pull request by rowleya**
This finally should fix the indexing issue, which was broken again when an application vertex was split by partitioning!  This also goes with a sPyNNaker8 branch which is fixing another issue but also running the integration tests for this fix...

### CODE REVIEW

**Comment by rowleya** [comment]
Still not quite there - I'll keep trying!

**Comment by andrewgait** [comment]
This was how I fixed this issue last time I saw it: https://github.com/SpiNNakerManchester/sPyNNaker/pull/668/files - not sure how that fits with this fix.

**Comment by rowleya** [comment]
Not sure - I removed that bit as it was causing other issues, but I have something in place now that just asks the master pop table for the index, since that is where it is supposed to be from...

**Comment by rowleya** [comment]
OK, it now seems to work everywhere finally!

**Pull request merged**
