### PR TITLE
fix sdram overuse

### PR DESCRIPTION
**Pull request by rowleya**
Added a multiplication to avoid too much SDRAM being used in very large networks (comes up with the Microcircuit example)

### CODE REVIEW

**Comment by rowleya** [comment]
Fixes #244

**Comment by alan-stokes** [comment]
magic number please name

**Comment by alan-stokes** [comment]
isn't this to avoid too little sdram being used? not too much sdram (as then id expect a divide) and it smacks of a fudge. Is there a better solution?

**Comment by rowleya** [comment]
A fudge it is, but the memory use is statistical.  This certainly allows us to run the microcircuit, which we can't without...

**Comment by rowleya** [comment]
It avoids us over-using the SDRAM in the synapses - if we do this on all cores on a chip we get an "out-of-memory" error when allocating recording regions (as these are done by the core now).

**Comment by alan-stokes** [comment]
ok, used vs allocated logic viewpoint. fair cope. and i know, just find fudges to be things that bite us later. lol.

**Comment by rowleya** [comment]
This is unlikely to cause new issues as it is just adding more memory to the estimate - so you might get less neurons per core with a large network I guess.  We might get more similar issues later that mean we need to revise this upwards again

**Pull request merged**
