### PR TITLE
Array connector

### PR DESCRIPTION
**Pull request by andrewgait**
Work to support using an ArrayConnector on the toolchain; basically, as simple as it sounds: the user supplies a 2D array of neuron IDs specifying the connections and this is simply passed into the synaptic blocks as required.

### CODE REVIEW

**Comment by andrewgait** [comment]
I ought also to have said in the description that although this sounds straightforward, it actually gives us a basis on which to set up the CSAConnector, which will be the next one I look at.  (CSA: Connection Set Algebra, there's a paper on it that I've read and a Python implementation which can be easily pip-installed and from what I've checked today, the results of using it can be quite easily converted into an array and fed through an ArrayConnector).

**Comment by andrewgait** [comment]
Just realised that this is a really basic version of the array connector which only works when the array is the same size as the number of (pre)-neurons... I'll need to do some more work to make this work for a general array.

**Comment by alan-stokes** [comment]
oh well, new pr it be then i guess.

**Comment by andrewgait** [comment]
Yeah - no problem, it's good to have something to work from anyway.

**Comment by andrewgait** [comment]
New PR is at: https://github.com/SpiNNakerManchester/sPyNNaker/pull/496

**Pull request merged**
