### PR TITLE
test small world split no random

### PR DESCRIPTION
**Pull request by Christian-B**
This shows the small world connector is BROKEN if the vertex is split.

The tests remove all randomness/ rewiring.

### CODE REVIEW

**Comment by Christian-B** [comment]
Intentionally not fixing the pylint issues so it fails actions and can not be merged as the many core test fails!

**Comment by Christian-B** [comment]
Still showing connectors broken

**Comment by Christian-B** [comment]
Assume this is no longer needed

**Comment by rowleya** [comment]
Believed now fixed

**Pull request closed without merging**
