### PR TITLE
Add option to ExternalLifNeurons to shift the value range of payloads

### PR DESCRIPTION
**Pull request by georghinkel**
This is to implement #492:

> Neurons using the neuron model above are supposed to regularly send their membrane potentials as a multicast command packet with payload where the payload equals to the current membrane potential. They do that, but the membrane potential is sent as an integer instead of an S1615. This loses a lot of precision and sometimes drops the whole point of these devices as these membrane potentials often fall below 1.

The way this is implemented is to interpret the integer value `value_as_payload` as a scaling factor instead of a boolean: If this scaling factor is 0, then no payload is required. In other cases, the value depicts an integer scaling factor. This scaling factor is set to a default of 1 in the Python API in order to give the equivalent behavior for existing code.

Unfortunately, I have no idea whether there are unit tests for the neuron models. Therefore, I did not alter any tests.

### CODE REVIEW

**Comment by georghinkel** [comment]
The build seems to fail because of the following lines:

> The command "flake8 examples spynnaker pyNN-spiNNaker-src" exited with 1.
> flake8 unittests

However, all I can see above is that all tests still pass. Do you have an idea why Travis failed?

**Comment by Christian-B** [comment]
After running the unittest travis does pep8 style checking using a program called flake8.

As the Travis output (reachable by the details link above) shows

**$ flake8 examples spynnaker pyNN-spiNNaker-src
spynnaker/pyNN/external_devices_models/threshold_type_multicast_device_control.py:54:80: E501 line too long (98 > 79 characters)**

length lines is one of many restrictions in pep8

**Comment by georghinkel** [comment]
I corrected the line length and fixed the test coverage problem. Is there anything else I need to do to get this merged?

**Comment by andrewgait** [comment]
I don't think so - it just needs one of us to review it and merge.  Someone should get to it in the near future...

**Pull request merged**
