### PR TITLE
Do the correct calculation for partitioning

### PR DESCRIPTION
**Pull request by andrewgait**
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/798

Tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/377

### CODE REVIEW

**Comment by rowleya** [comment]
Looks OK; does it help with the issue?

**Comment by andrewgait** [comment]
It doesn't fail at the partitioning stage any more - I admit that I did leave that script running after I left the office yesterday and got a different error, but I don't think it's necessarily related to this.  Perhaps we should wait for @ej159 to get back to us, as it's his script after all...

**Comment by ej159** [comment]
This fixes that problem for up to about 32 kernels in the test script. Above this I get a SynapticConfigurationException `SynapticConfigurationException: Address 0x802c810 is out of range for this population table!`. Presumably that's just too many kernel to expand?

**Comment by rowleya** [comment]
So that could mean that the size is still vastly overestimating...

**Comment by andrewgait** [comment]
Will look at this again - could be that the estimate of the max number of connections to each post-neuron is also overestimated...

**Comment by andrewgait** [comment]
Hi @ej159, I've been experimenting a bit more with your script, and the real issue actually seems to be the choice to run at a low number of neurons per core.  I'm not sure in terms of what you're trying to do whether this is necessary or not - I've found that increasing the number of neurons per core (for both populations) up to say 64 or even 128 seems to help a lot in terms of running this script (as an example, it currently takes ~20 minutes from start to finish to run 96 kernels at 128 neurons per core, which is much faster than anything I've seen when running at 16 neurons per core, even for a very low number of kernels).  I'm guessing this is because the data is more spread out across the machine and therefore simply just takes longer to be (sequentially) copied everywhere, but that's something of a guess.  Note here too that using Java helps with this script as the network is spread across 3 boards and therefore the data loading time vs. Python is reduced.

(I believe I have now improved the partitioning calculations on this branch so that you won't see pop-table address errors until you get to somewhere over 100 kernels; if you need more than that then there may be more we can do).

**Comment by andrewgait** [comment]
I think the (necessary) fixes on this branch are ready to go in now.  

In the actual cases @ej159 and @such-a-git are trying to run, the problems are in general due to the size of the source populations; the suggested workaround in this case is to split up single source or target populations in to multiple separate populations as appropriate.

To give some more information, the memory size for a synaptic matrix is memory_size = n_atoms x row_size x n_kernels, even if row_size is small, will cause problems when n_atoms is big. In one case I have been looking at, the pre-pop is the whole "image" simulated as an SSA, so 304 x 240 = 72960 atoms. The post-pop is the same size as the number of filters/kernels applied - so something like row_size = (n_kernels + 3) * 4 (the 3 here is the fixed header size of a synaptic row). So 

memory_size = 72960 * n_kernels * [(n_kernels + 3) * 4].  

Limiting this to the SDRAM available using 128MB gives: 

n_kernels^2 + 3*n_kernels = ~438 

and solving this gives ~20 kernels in this case.  As you can see, the ways to reduce this are to reduce the number of kernels and/or the sizes of the populations.

What this doesn't explain entirely is why the "same" FromListConnectors are apparently working - more investigation of this (by @ej159 and @such-a-git) would be welcome...

**Comment by alan-stokes** [comment]
could it be that the calcs for max row length for the from list is more accurate than that of the kernel conenctor?

**Comment by andrewgait** [comment]
> could it be that the calcs for max row length for the from list is more accurate than that of the kernel conenctor?

We've discussed this previously and we don't think so - if the FromList is creating the same connections as the KernelConnector then the calculations should be the same.

**Comment by alan-stokes** [comment]
same connections yes. but if the max row length is off. different sizes of padding's. which in turn makes different max size. Basically, as a possible scope to find a bug. is the padding the same?

**Comment by andrewgait** [comment]
> same connections yes. but if the max row length is off. different sizes of padding's. which in turn makes different max size. Basically, as a possible scope to find a bug. is the padding the same?

I'm sure that the max row length should be the same in each case.  Whether it is or not is dependent on whether the function to create the FromList is actually reproducing what the Kernel is actually doing (I suspect not, hence the discrepancy).

**Comment by andrewgait** [comment]
This has been tested by @such-a-git with the "iCub simulator" and seems to be working, so I think it's ready to be merged.

**Pull request merged**
