### PR TITLE
added 3.9 and rat 3.8 (more like other repr)

### PR DESCRIPTION
**Pull request by Christian-B**
python_actions changed to be more like other repositories

### CODE REVIEW

**Review by dkfellows — CHANGES_REQUESTED** [review]
I reject the removal of `validate` and `doc-check` builds. The latter especially; documentation checks take a long time in sPyNNaker now.

**Comment by Christian-B** [comment]
> I reject the removal of `validate` and `doc-check` builds. The latter especially; documentation checks take a long time in sPyNNaker now.

I understand these can take a while but I don't understand the need to redo the exact same step stages various times.

**Comment by dkfellows** [comment]
The reason for duplicating the installation steps? Hmm… 🤔 

The validation steps can be merged in though. It's only the documentation test-build that I'd really like to get in parallel with the others, for reasons discussed in #989. (The phases that can take quite a while are installation, test running, and doc running. Installation is a prerequisite for the other two, and the mechanisms for sharing a configured build are unlikely to help speed things up very much.)

**Comment by dkfellows** [comment]
See #1003 for an improvement (with analysis) I want to see in this branch.

**Review by dkfellows — APPROVED** [review]

**Pull request merged**
