### PR TITLE
Deal with cases with mixed list and RandomDistribution, add tests

### PR DESCRIPTION
**Pull request by andrewgait**
Deal with the case where weights / delays are not given in a FromListConnector and are specified using RandomDistribution in the StaticSynapse.

Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/22

### CODE REVIEW

**Review by rowleya — APPROVED** [review]
Looks good - merge when integration is green!

**Comment by Christian-B** [comment]
Approved to merge

**Comment by Christian-B** [comment]
Looks like you need to relax the almost equals a bit more

**Comment by Christian-B** [comment]
Agree with the changes still good to merge when integeration green

**Pull request merged**
