### PR TITLE
Validate mars kiss seeds before use

### PR DESCRIPTION
**Pull request by andrewgait**
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/886 (and a few more places where this issue was also discovered).

Tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/504 (which also needs merging as the tests using fixed seeds needed to be updated).

### CODE REVIEW

**Comment by alan-stokes** [comment]
can approve this, but it begs a question. is the seed default better if its set to None in the utility function? 
also, if there is no rng, dont we want to report the seed of the rng somehow?

**Review by alan-stokes — APPROVED** [review]

**Comment by andrewgait** [comment]
> can approve this, but it begs a question. is the seed default better if its set to None in the utility function?
> also, if there is no rng, dont we want to report the seed of the rng somehow?

I think the short answer to the first question is "Yes", but we should probably allow someone to set a seed when using this function if they really want to.

I'm not sure I understand your second question; numpy appears to cope fine with numpy.random.RandomState(None)...

**Comment by alan-stokes** [comment]
> I think the short answer to the first question is "Yes", but we should probably allow someone to send in a seed when using this function if they really want to.

in this i meant. that in utility functiuons. change seed to seed=None. as it seems thats the default.

**Comment by alan-stokes** [comment]
> I'm not sure I understand your second question; numpy appears to cope fine with numpy.random.RandomState(None)...

it occured to me. if you have no rng, and no seed. your getting a random seed. thus should the prov data report that seed so that future users could acutally reproduce the work?

**Comment by andrewgait** [comment]
> > I'm not sure I understand your second question; numpy appears to cope fine with numpy.random.RandomState(None)...
> 
> it occured to me. if you have no rng, and no seed. your getting a random seed. thus should the prov data report that seed so that future users could acutally reproduce the work?

With no rng and no seed, you get a whole new rng (with seed=None).  The future user would then have to bypass this to directly set kiss_seed, wouldn't they?

**Comment by andrewgait** [comment]
> > I think the short answer to the first question is "Yes", but we should probably allow someone to send in a seed when using this function if they really want to.
> 
> in this i meant. that in utility functiuons. change seed to seed=None. as it seems thats the default.

Done.

**Comment by alan-stokes** [comment]
> > > I'm not sure I understand your second question; numpy appears to cope fine with numpy.random.RandomState(None)...
> > 
> > 
> > it occured to me. if you have no rng, and no seed. your getting a random seed. thus should the prov data report that seed so that future users could acutally reproduce the work?
> 
> With no rng and no seed, you get a whole new rng (with seed=None). The future user would then have to bypass this to directly set kiss_seed, wouldn't they?

you'd get a new rng. but i presume there's gotta be some seed for said rng, isnt None just a misnomer for random seed. So by putting said new seed in prov, the user can then get the information if they do desire a repeatable run by seeding their rngs the second time around.

**Comment by alan-stokes** [comment]
> numpy.random.RandomState(None).

Random seed used to initialize the pseudo-random number generator. Can be any integer between 0 and 2**32 - 1 inclusive, an array (or other sequence) of such integers, or None (the default). If seed is None, then RandomState will try to read data from /dev/urandom (or the Windows analogue) if available or seed from the clock otherwise.
https://numpy.org/doc/1.13/reference/generated/numpy.random.RandomState.html

which says theres some seed, just where it gets said seed, is from some psuedo random location, and is os specific.

**Comment by alan-stokes** [comment]
im not saying it needs to be done here. it was that here was what sparked the question.

**Comment by andrewgait** [comment]
> > numpy.random.RandomState(None).
> 
> Random seed used to initialize the pseudo-random number generator. Can be any integer between 0 and 2**32 - 1 inclusive, an array (or other sequence) of such integers, or None (the default). If seed is None, then RandomState will try to read data from /dev/urandom (or the Windows analogue) if available or seed from the clock otherwise.
> https://numpy.org/doc/1.13/reference/generated/numpy.random.RandomState.html
> 
> which says theres some seed, just where it gets said seed, is from some psuedo random location, and is os specific.

Ah, okay.  Looking into this a bit further, it is possible to reproduce - you'd need to use the RandomState.get_state() function, put that into provenance somewhere, and then a user can get it back by building their own rng and using the set_state() function.

**Pull request merged**
